// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJdxVfn9vJEYveKFuJwSc8l4q6Xj_ki0o',
    appId: '1:1032703088391:web:36a96cea7747312f7ed7a2',
    messagingSenderId: '1032703088391',
    projectId: 'profim-518d6',
    authDomain: 'profim-518d6.firebaseapp.com',
    storageBucket: 'profim-518d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeoDu0_VNF0oQEbTaJzf960dgI2NtS0Ws',
    appId: '1:1032703088391:android:451bf8a27b6b2f127ed7a2',
    messagingSenderId: '1032703088391',
    projectId: 'profim-518d6',
    storageBucket: 'profim-518d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01iMJBOr3mxPgqrNqJb2s0Czw3UrBy6g',
    appId: '1:1032703088391:ios:14d604eae78897837ed7a2',
    messagingSenderId: '1032703088391',
    projectId: 'profim-518d6',
    storageBucket: 'profim-518d6.firebasestorage.app',
    iosBundleId: 'com.example.profiminspectionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01iMJBOr3mxPgqrNqJb2s0Czw3UrBy6g',
    appId: '1:1032703088391:ios:14d604eae78897837ed7a2',
    messagingSenderId: '1032703088391',
    projectId: 'profim-518d6',
    storageBucket: 'profim-518d6.firebasestorage.app',
    iosBundleId: 'com.example.profiminspectionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJdxVfn9vJEYveKFuJwSc8l4q6Xj_ki0o',
    appId: '1:1032703088391:web:a0f4cb4a268499eb7ed7a2',
    messagingSenderId: '1032703088391',
    projectId: 'profim-518d6',
    authDomain: 'profim-518d6.firebaseapp.com',
    storageBucket: 'profim-518d6.firebasestorage.app',
  );
}
